### ISSUE TITLE
Power calculation

### ISSUE THREAD

**Issue by reinestenberg** [rarvids4/homeassistant-blueprints-loadbalancing#1]
Row 184:
{% if (currentAvailableL3 < currentAvailableL2)%}

Shouldn't this be the other way around?

**Comment by rarvids4** [comment]
Currently some troubleshooting now on syntax error on: valCurrentAvailableForCharging.
 so I will solve this after finding the syntax error

**Comment by rarvids4** [comment]
It should be OK. If I knew how to use MIN() in YAML I would have written MIN(CurrentAvailableL1, ....LN)
