### ISSUE TITLE
More than one charger?

### ISSUE THREAD

**Issue by reinestenberg** [rarvids4/homeassistant-blueprints-loadbalancing#2]
You should consider using easee.set_circuit_dynamic_limit instead of easee.set_charger_dynamic_limit

Pros:
Load balancing works for more than one charger
Other software uses easee.set_charger_dynamic_limit (e.g. peaqev which limits the power usage to take Göteborg energi power tariffs into consideration.

Cons:
?

**Comment by rarvids4** [comment]
Very good feedback. I will change this instead, it simplifies alot
